const quotes = [
"La vida se trata de generar impacto, no de generar ingresos.|Kevin Kruse",
"Todo lo que la mente del hombre pueda concebir y creer, puede lograrlo.|Napoleon Hill",
"Esfuérzate no por ser un éxito, sino por ser de valor.|Albert Einstein",
"Dos caminos se bifurcaban en un bosque, y yo—yo tomé el menos transitado, y eso marcó toda la diferencia.|Robert Frost",
"A esto atribuyo mi éxito: nunca di ni tomé ninguna excusa.|Florence Nightingale",
"Fallas el 100% de los tiros que no haces.|Wayne Gretzky",
"He fallado más de 9000 tiros en mi carrera. He perdido casi 300 juegos. 26 veces me han confiado para tomar el tiro ganador y he fallado. He fallado una y otra y otra vez en mi vida Y por eso lo logro.|Michael Jordan",
"Lo más difícil es la decisión de actuar, el resto es mera tenacidad.|Amelia Earhart",
"Cada strike me acerca al próximo jonrón.|Babe Ruth",
"La definición del propósito es el punto de partida de todo logro. –W.|Clement Stone",
"La vida no se trata de conseguir y tener, se trata de dar y ser.|Kevin Kruse",
"La vida es lo que te pasa mientras estás ocupado haciendo otros planes.|John Lennon",
"Nos convertimos en lo que pensamos sobre|Earl Nightingale",
"Dentro de veinte años estarás más decepcionado por las cosas que no hiciste que por las que hiciste, así que tira las amarras, navega lejos del puerto seguro, atrapa los vientos alisios en tus velas. Explora, sueña , Descubrir.|Mark Twain",
"La vida es un 10% de lo que me pasa y un 90% de cómo reacciono ante ello.|Charles Swindoll",
"La forma más común en que las personas renuncian a su poder es pensando que no lo tienen. Alice Walker",
"La mente lo es todo. En lo que crees te conviertes.|Buda",
"El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.|Proverbio chino",
"Una vida no examinada no vale la pena ser vivida.|Sócrates",
"El ochenta por ciento del éxito está apareciendo. Woody Allen",
"Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona.|Steve Jobs",
"Ganar no lo es todo, pero querer ganar sí lo es.|Vince Lombardi",
"No soy producto de mis circunstancias. Soy producto de mis decisiones.|Stephen Covey",
"Todo niño es un artista. El problema es cómo seguir siendo artista una vez que crece.|Pablo Picasso",
"Nunca puedes cruzar el océano hasta que tengas el coraje de perder de vista la orilla.|Cristóbal Colón",
"He aprendido que la gente olvidará lo que dijiste, la gente olvidará lo que hiciste, pero la gente nunca olvidará cómo los hiciste sentir.|Maya Angelou",
"O tú diriges el día, o el día te dirige a ti.|Jim Rohn",
"Tanto si crees que puedes como si crees que no puedes, tienes razón.|Henry Ford",
"Los dos días más importantes de tu vida son el día que naces y el día que descubres por qué.|Mark Twain",
"Cualquier cosa que puedas hacer, o sueñes que puedes hacer, comienza. La audacia tiene genio, poder y magia en ella.|Johann Wolfgang von Goethe",
"La mejor venganza es el éxito masivo.|Frank Sinatra",
"La gente suele decir que la motivación no dura. Bueno, el baño tampoco. Por eso lo recomendamos a diario.|Zig Ziglar",
"La vida se encoge o se expande en proporción al coraje de uno.|Anais Nin",
"Si escuchas una voz dentro de ti que dice 'no puedes pintar', entonces pinta y esa voz será silenciada.|Vincent Van Gogh",
"Solo hay una forma de evitar la crítica: no hacer nada, no decir nada y ser nada.|Aristóteles",
"Pedid y se os dará; buscad y hallaréis; llamad y se os abrirá la puerta.|Jesús",
"La única persona en la que estás destinado a convertirte es la persona que decidas ser.|Ralph Waldo Emerson",
"Ve con confianza en la dirección de tus sueños. Vive la vida que has imaginado.|Henry David Thoreau",
"Cuando me presente ante Dios al final de mi vida, espero que no me quede ni un poco de talento y pueda decir, usé todo lo que me diste.|Erma Bombeck",
"Pocas cosas pueden ayudar más a una persona que responsabilizarla y hacerle saber que confías en ella. –Booker T. Ashington",
"Ciertas cosas te llaman la atención, pero persigue solo aquellas que capturan el corazón.|Proverbio indio antiguo",
"Cree que puedes y estás a mitad de camino.|Theodore Roosevelt",
"Todo lo que siempre quisiste está al otro lado del miedo.|George Addair",
"Podemos perdonar fácilmente a un niño que tiene miedo a la oscuridad; la verdadera tragedia de la vida es cuando los hombres tienen miedo a la luz.|Platón",
"Enseña a tu lengua a decir: 'No sé', y progresarás.|Maimónides",
"Empieza donde estás. Usa lo que tienes. Haz lo que puedas.|Arthur Ashe",
"Cuando tenía 5 años, mi madre siempre me decía que la felicidad era la clave de la vida. Cuando iba a la escuela, me preguntaban qué quería ser cuando fuera grande. Escribí 'feliz'. Me dijeron No entendí la tarea, y les dije que no entendían la vida.|John Lennon",
"Cae siete veces y levántate ocho. Proverbio japonés",
"Cuando una puerta de la felicidad se cierra, otra se abre, pero muchas veces miramos tanto la puerta cerrada que no vemos la que se ha abierto para nosotros.|Helen Keller",
"Todo tiene belleza, pero no todos pueden ver.|Confucio",
"Qué maravilloso es que nadie tenga que esperar un solo momento antes de empezar a mejorar el mundo.|Ana Frank",
"Cuando dejo ir lo que soy, me convierto en lo que podría ser.|Lao Tse",
"La vida no se mide por el número de respiraciones que hacemos, sino por los momentos que nos quitan el aliento.|Maya Angelou",
"La felicidad no es algo prefabricado. Viene de tus propias acciones.|Dalai Lama",
"Si te ofrecen un asiento en un cohete espacial, ¡no preguntes qué asiento! Solo súbete.|Sheryl Sandberg",
"Primero, ten un ideal práctico claro y definido; una meta, un objetivo. Segundo, ten los medios necesarios para lograr tus fines; sabiduría, dinero, materiales y métodos. Tercero, ajusta todos tus medios a ese fin.|Aristóteles" ,
"Si el viento no sirve, toma los remos.|Proverbio latino",
"No puedes caerte si no trepas. Pero no hay alegría en vivir toda tu vida en el suelo.|Desconocido",
"Debemos creer que estamos dotados para algo, y que eso, cueste lo que cueste, hay que conseguirlo.|Marie Curie",
"Muchos de nosotros no estamos viviendo nuestros sueños porque estamos viviendo nuestros miedos.|Les Brown",
"Los desafíos son los que hacen que la vida sea interesante y superarlos es lo que hace que la vida tenga sentido.|Joshua J. Marine",
"Si quieres levantarte a ti mismo, levanta a alguien más. –Booker T.|ashington",
"Me ha impresionado la urgencia de hacer. No basta con saber, hay que aplicar. No basta con querer, hay que hacer.|Leonardo da Vinci",
"Las limitaciones viven solo en nuestra mente. Pero si usamos nuestra imaginación, nuestras posibilidades se vuelven ilimitadas.|Jamie Paolinetti",
"Tomas tu vida en tus propias manos, ¿y qué pasa? Algo terrible, nadie a quien culpar.|Erica Jong",
"¿Qué es el dinero? Un hombre es un éxito si se levanta por la mañana y se acuesta por la noche y en el medio hace lo que quiere hacer.|Bob Dylan",
"No reprobé la prueba. Solo encontré 100 formas de hacerlo mal.|Benjamin Franklin",
"Para tener éxito, tu deseo de éxito debe ser mayor que tu miedo al fracaso.|Bill Cosby",
"Una persona que nunca cometió un error, nunca intentó nada nuevo.|Albert Einstein",
"La persona que dice que no se puede hacer no debe interrumpir a la persona que lo está haciendo. Proverbio chino",
"No hay atascos en la milla extra.|Roger Staubach",
"Nunca es demasiado tarde para ser lo que podrías haber sido.|George Eliot",
"Te conviertes en lo que crees.|Oprah Winfrey",
"Prefiero morir de pasión que de aburrimiento.|Vincent van Gogh",
"Un hombre verdaderamente rico es aquel cuyos hijos corren a sus brazos cuando sus manos están vacías. Desconocido",
"No es lo que haces por tus hijos, sino lo que les has enseñado a hacer por sí mismos, lo que los convertirá en seres humanos exitosos.|Ann Landers",
"Si quieres que tus hijos salgan bien, pasa el doble de tiempo con ellos y la mitad de dinero.|Abigail Van Buren",
"Construye tus propios sueños, o alguien más te contratará para construir los suyos. Farrah Gray",
"Las batallas que cuentan no son las de las medallas de oro. Las luchas dentro de ti, las batallas invisibles dentro de todos nosotros, ahí es donde está.|Jesse Owens",
"La educación cuesta dinero. Pero también la ignorancia.|Sir Claus Moser",
"He aprendido con los años que cuando uno está decidido, esto disminuye el miedo.|Rosa Parks",
"No importa lo lento que vayas mientras no te detengas.|Confucio",
"Si miras lo que tienes en la vida, siempre tendrás más. Si miras lo que no tienes en la vida, nunca tendrás suficiente.|Oprah Winfrey",
"Recuerda que no conseguir lo que quieres es a veces un maravilloso golpe de suerte.|Dalai Lama",
"No puedes agotar la creatividad. Cuanto más usas, más tienes.|Maya Angelou",
"Sueña en grande y atrévete a fallar.|Norman Vaughan",
"Nuestras vidas comienzan a terminar el día que guardamos silencio sobre las cosas que importan.|Martin Luther King Jr.",
"Haz lo que puedas, donde estés, con lo que tengas.|Teddy Roosevelt",
"Si haces lo que siempre has hecho, obtendrás lo que siempre has obtenido.|Tony Robbins",
"Soñar, después de todo, es una forma de planificación.|Gloria Steinem",
"Es tu lugar en el mundo; es tu vida. Sigue adelante y haz todo lo que puedas con él, y haz que sea la vida que quieres vivir.|Mae Jemison",
"Puede que te decepciones si fallas, pero estás condenado si no lo intentas.|Beverly Sills",
"Recuerda que nadie puede hacerte sentir inferior sin tu consentimiento.|Eleanor Roosevelt",
"La vida es lo que hacemos, siempre lo ha sido, siempre lo será.|Abuela Moses",
"La pregunta no es quién me va a dejar, es quién me va a detener.|Ayn Rand",
"Cuando todo parezca ir en tu contra, recuerda que el avión despega contra el viento, no con él.|Henry Ford",
"No son los años de tu vida los que cuentan. Es la vida de tus años.|Abraham Lincoln",
"Cambia tus pensamientos y cambiarás tu mundo.|Norman Vincent Peale",
"Escribe algo que valga la pena leer o haz algo que valga la pena escribir.|Benjamin Franklin",
"Nada es imposible, la palabra misma dice: '¡Soy posible!'|Audrey Hepburn",
"La única forma de hacer un gran trabajo es amar lo que haces.|Steve Jobs",
"Si puedes soñarlo, puedes lograrlo.|Zig Ziglar"
];

const randomQuotesGenerator = () => {
  const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
  console.log(randomQuote);
}

module.exports = {randomQuotesGenerator};